export type Sex = "female" | "male" | "other" | "unknown";
export type TriState = "yes" | "no" | "unknown";
export interface Facility { id: string; name: string; astUln: number | null; altUln: number | null; alpUln: number | null; iggUln: number | null; sweUnit: "kPa" | "m/s" | null; sweCutoff: number | null; performsTransplant: TriState; }
export type FacilitySnapshot = Readonly<Facility>;
export interface Labs { age?: number|null; ast?: number|null; alt?: number|null; platelets?: number|null; totalBilirubin?: number|null; albumin?: number|null; inr?: number|null; creatinine?: number|null; sodium?: number|null; igg?: number|null; wbc?: number|null; ptActivity?: number|null; ptSeconds?: number|null; controlPtSeconds?: number|null; weight?: number|null; }
export interface Findings { ascites?: "none"|"controlled"|"refractory"|"unknown"; encephalopathy?: "none"|"grade12"|"grade34"|"yes"|"unknown"; liverAtrophy?: TriState; dialysis?: TriState; renalInsufficiency?: TriState; ana?: string; asma?: string; lkm1?: TriState; slaLp?: TriState; histology?: "typical"|"compatible"|"atypical"|"unknown"; steroidResponse?: "marked"|"other"|"unknown"; viralExcluded?: TriState; otherCausesExcluded?: TriState; dic?: boolean; gastrointestinalBleeding?: boolean; bacterialInfection?: boolean; }
export interface Assessment { id:string; label:string; timing:{absoluteDate:string|null;relativeDay:number|null}; age:number|null; facilitySnapshot:FacilitySnapshot|null; labs:Labs; findings:Findings; treatments:Record<string, unknown>; selectedClinicalContexts:string[]; note:string; }
export interface Medication { id:string; name:string; start:{absoluteDate:string|null;relativeDay:number|null}; stop:{absoluteDate:string|null;relativeDay:number|null}; reexposure:"yes"|"no"|"unknown"; suspicion:"high"|"possible"|"low"|"unknown"; note:string; }
export interface CaseRecord { schemaVersion:3; id:string; caseCode:string; demographics:{sex:Sex;ageAtBaseline:number|null}; baselineDate:string|null; assessments:Assessment[]; medications:Medication[]; createdAt:string; updatedAt:string; }
export interface Backup { schemaVersion:3; appVersion:string; exportedAt:string; facilities:Facility[]; cases:CaseRecord[]; }
