name: Pull Request checks
on: { pull_request: {} }
permissions: { contents: read }
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with: { node-version: 22 }
      - run: npm ci
      - run: npm run format:check
      - run: git diff --exit-code -- package-lock.json
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test:unit
      - run: npm run test:component
      - run: npm run test:legacy
      - run: npm run build
        env: { GITHUB_SHA: "${{ github.event.pull_request.head.sha }}" }
      - run: npm audit --omit=dev --audit-level=high
      - if: github.event.pull_request.head.repo.full_name == github.repository
        run: |
          npm exec playwright install --with-deps chromium
          npm run screenshots
      - if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: production-build-pr-${{ github.event.number }}-${{ github.event.pull_request.head.sha }}
          path: dist
          retention-days: 14
      - if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: screenshots-pr-${{ github.event.number }}-${{ github.event.pull_request.head.sha }}
          path: screenshots
          retention-days: 14
